echo Please wait...
echo Moving libs to $HOME/cxl/lib...
mkdir -p $HOME/cxl/
cp -r lib $HOME/cxl/
echo Moving compiler to $HOME/cxl/...
cp cxlc.py $HOME/cxl/
echo Creating aliases...
echo "alias cxlc='python3 $HOME/cxl/cxlc.py'" >> ~/.bashrc
echo "alias cxlc='python3 $HOME/cxl/cxlc.py'" >> ~/.bash_profile
echo Done!
