name: Lint

on:
  push:
    branches: [ "master" ]
    paths:
      - "lib/**"
      - "cxlc.py"
  pull_request:
    branches: [ "master" ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Install flake8
      run: pip install flake8
    - uses: actions/checkout@v4
    - name: Lint with flake8
      run: flake8 ./cxlc.py
    - name: Finalize
      run: python3 cxlc.py --moo
