name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Lint with flake8
      run: flake8 ./cxlc.py
    - name: Finalize
      run: python3 cxlc.py --moo
